
export const keywords = [
    "Umini",
    "Projetos elétricos",
    "Automação residencial",
    "Eficiência energética",
    "Sustentabilidade",
    "Inovação tecnológica",
    "Conforto residencial",
    "Segurança eletrônica",
    "Soluções inteligentes",
    "Tecnologia verde",
    "energia",
    "eletrica",
    "residencial",
    "automação",
    "sustentabilidade",
    "inovação",
    "tecnologia",
    "segurança",
    "conforto",
    "projetos",
    "projeto eletrico",
    "ecnonomia",
    "economia de energia",
    "marte software",
    "desenvolvimento web",
    "diferenca",
    "projetos eletricos",
    "brasil",
    "homologacao",
    "obras",
    "empresa de projetos",
    "engenharia",
    "engenharia eletrica",
    "modernização",
    "consultoria tecnica",
    "modelagem 3d",
    "modelagem",
    "3d",
    "equipe tecnica",
    "qualidade",
    "atendimento",
    "suporte tecnico",
    "clientes",
]